Docker unattended-upgrades
konstruktoid/ansible-role-docker-rootless pull request #437
Opened 2024-08-14 10:46 UTC by msladek

I run Debian instances with [unattended-upgrades](https://wiki.debian.org/UnattendedUpgrades) installed. When applying this role to some of those servers the packages from the Docker repo don't get automatically updated since the package control `Unattended-Upgrade::Origins-Pattern` for Docker is missing.

This PR adds this configuration for Debian systems during rootful installation in case the package `unattended-upgrades` is installed. It does nothing otherwise.

2024-08-14 10:55 UTC, konstruktoid commented
I like the idea and `[unattended-upgrades](https://wiki.debian.org/UnattendedUpgrades)` but it needs to be a variable with default `false`, if people dont use `live-restore` alot of systems will be crashing down.

2024-08-16 20:56 UTC, msladek commented
@konstruktoid I've added a variable to make sure it isn't accidentality configured.

2024-08-20 06:20 UTC, konstruktoid requested changes
So sorry for the delay!
There are a couple of improvements, and it needs `become` to write the config file.

```diff
diff --git a/molecule/default/molecule.yml b/molecule/default/molecule.yml
index 09eece4..10f4e11 100644
--- a/molecule/default/molecule.yml
+++ b/molecule/default/molecule.yml
@@ -62,6 +62,7 @@ provisioner:
         docker_allow_privileged_ports: false
         docker_rootful: true
         docker_rootful_enabled: false
+        docker_unattended_upgrades: true
         docker_user: dockeruser
         docker_user_bashrc: false
         docker_compose: false
diff --git a/tasks/docker_install_rootful.yml b/tasks/docker_install_rootful.yml
index 5b9b503..32f7edb 100644
--- a/tasks/docker_install_rootful.yml
+++ b/tasks/docker_install_rootful.yml
@@ -29,15 +29,18 @@
         manager: auto

     - name: Unattended upgrades for Docker
+      become: true
       ansible.builtin.lineinfile:
         path: /etc/apt/apt.conf.d/55unattended-upgrades-docker
-        line: 'Unattended-Upgrade::Origins-Pattern { "o=Docker,a=${distro_codename}"; };'
+        line: Unattended-Upgrade::Origins-Pattern { "o=Docker,a=${distro_codename}"; };
         state: present
         create: true
         owner: root
         group: root
         mode: "0644"
-      when: docker_unattended_upgrades | bool and 'unattended-upgrades' in ansible_facts.packages
+      when:
+        - docker_unattended_upgrades | bool
+        - "'unattended-upgrades' in ansible_facts.packages"

     - name: Run apt update
       become: true
```

2024-11-08 21:48 UTC, msladek commented
@konstruktoid the patch is applied, sorry for hiatus

2024-11-11 20:38 UTC, konstruktoid requested changes

2024-11-11 20:38 UTC, konstruktoid commented on tasks/docker_install_rootful.yml
> +        when:
wrong identation

2024-11-11 20:39 UTC, konstruktoid commented
> @konstruktoid the patch is applied, sorry for hiatus

no worries whatsoever, thanks for updating it

2024-11-20 08:40 UTC, konstruktoid approved these changes

2024-11-24 18:11 UTC, konstruktoid commented
So sorry for the delay, and thank you for the PR

2024-11-24 18:11 UTC, merged